#!/bin/bash

# $1: mail_from
# $2: mail_to 
# $3: subject 
# $4: msgBody

# 注意，输入参数时候要把输入的参数用引号引起来，防止发送邮件的时候丢失信息
function send_email(){

	from="$1"					# 发送自
	toEmail="$2" 					# 发送到
	subject="$3" 					# 标题
	msgBody="$4"					# 要发送的信息体
	msgDate="$5" 					# 日期
	temp="/tmp/sendmail.tmp"
	date=`date +%F`

	echo -e "From: ${from}" > ${temp}
	echo -e "To: ${toEmail}" >> ${temp}
	echo -e "Subject: ${subject}" >> ${temp}
	echo -e "Content-Type: text/html; charset=utf-8; format=flowed" >> ${temp}
	echo -e "Content-Transfer-Encoding: 7bit" >> ${temp}
	echo -e "Content-Disposition: inline" >> ${temp}
	echo -e "" >> ${temp}
	echo -e "${msgBody}" >> ${temp}
	echo -e "" >> ${temp}
	echo -e "${msgDate}" >> ${temp}
	echo -e "" >> ${temp}

	cat ${temp} | sendmail -t;
	rm -fr ${temp}
}



